apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello
  name: hello-app 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello 
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/kubernetes-403900/hello-repo/helloworld-gke:latest
        name: hello-app 
        ports:
        - containerPort: 8080
        env:
          - name: PORT 
            value: "8080"
        resources: 
          requests:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
status: {}
